# SPDX-License-Identifier: GPL-2.0
dtb-$(CONFIG_ARCH_ROCKCHIP) += \
	rk3588s-radxa-cm5-saturn-k612.dtb \
	rk3588s-radxa-cm5-saturn-8inch-k612.dtb

# Added by Armbian autopatcher for DT overlay
subdir-y       := $(dts-dirs) overlay
